import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));

const REQUIRED_ICONS = {
	mdi: [
		'close',
		'play',
		'pause',
		'volume-high',
		'volume-off',
		'keyboard',
		'cog',
		'send',
		'keyboard-outline',
		'chevron-down',
		'firework',
		'resize',
		'high-definition-box',
		'weather-night',
		'magnify-scan',
		'rocket-launch',
		'fire',
		'sine-wave',
		'eye-off',
		'message-off',
		'fullscreen',
		'camera-iris',
		'format-text',
		'palette',
		'shuffle-variant',
		'sort',
		'group',
		'counter',
		'help-circle-outline',
	],
	'circle-flags': ['zh', 'us'],
};

function extractIcons(prefix, iconNames) {
	const jsonPath = resolve(__dirname, `../node_modules/@iconify-json/${prefix}/icons.json`);
	const fullData = JSON.parse(readFileSync(jsonPath, 'utf-8'));

	const extracted = {
		prefix: fullData.prefix,
		icons: {},
	};

	if (fullData.width) extracted.width = fullData.width;
	if (fullData.height) extracted.height = fullData.height;
	if (fullData.left) extracted.left = fullData.left;
	if (fullData.top) extracted.top = fullData.top;

	let missing = [];
	for (const name of iconNames) {
		if (fullData.icons[name]) {
			extracted.icons[name] = fullData.icons[name];
		} else {
			missing.push(name);
		}
	}

	if (missing.length > 0) {
		console.warn(`[${prefix}] Missing icons: ${missing.join(', ')}`);
	}

	console.log(`[${prefix}] Extracted ${Object.keys(extracted.icons).length}/${iconNames.length} icons`);
	return extracted;
}

function generateIconDataFile() {
	const allData = [];

	for (const [prefix, iconNames] of Object.entries(REQUIRED_ICONS)) {
		allData.push(extractIcons(prefix, iconNames));
	}

	const outputDir = resolve(__dirname, '../src/ui/icons');
	mkdirSync(outputDir, { recursive: true });

	const outputPath = resolve(outputDir, 'icon-data.ts');

	const content = `// Auto-generated by scripts/extract-icons.mjs
// Do not edit manually. Run "pnpm generate-icons" to regenerate.

import type { IconifyJSON } from '@iconify/vue';

export const iconCollections: IconifyJSON[] = ${JSON.stringify(allData, null, '\t')};
`;

	writeFileSync(outputPath, content, 'utf-8');

	try {
		execSync(`npx prettier --write "${outputPath}"`, { stdio: 'pipe' });
		console.log('Formatted with Prettier');
	} catch {
		console.warn('Prettier formatting failed (install prettier as devDependency for auto-formatting)');
	}

	const finalContent = readFileSync(outputPath, 'utf-8');
	console.log(`\nIcon data written to: ${outputPath}`);
	console.log(`Total size: ${(Buffer.byteLength(finalContent, 'utf-8') / 1024).toFixed(1)} KB`);
}

generateIconDataFile();
